name: Run unit docker tests

on: [ push ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t my-image .
      - name: Run tests
        run: docker run my-image
      - name: Test files
        run: docker exec my-image pytest
