name: Spark Function Tests
on: 
  pull_request:
    branches:
      - 'qa'
jobs:
  pytest:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.1
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'
    - name: Install dependencies for tests
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Run pytest
      run: |
        python3 -m pytest
